server:
  name: hostel-service
  port: 8080

sql:
  driver: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5433
  database: postgres

# db: 'host=localhost user=postgres password=postgres dbname=postgres port=5433'
db: 'host=satao.db.elephantsql.com user=otrodoaa password=xCYt_r2HWQ97cyuuXlJfKoMpijxd6L_M dbname=otrodoaa port=5432'

log:
  level: info
  map:
    time: '@timestamp'
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

client:
  endpoint:
    url: 'http://localhost:8080/hostels'
    timeout: 1s
  log:
    log: true
    size: size
    status: status
    request: request
    response: response
