basePath: /
definitions:
  domain.GetHostelsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Hostel'
        type: array
      pagination:
        $ref: '#/definitions/util.Pagination'
    type: object
  domain.GetTeamMembersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.TeamMember'
        type: array
      pagination:
        $ref: '#/definitions/util.Pagination'
    type: object
  domain.Hostel:
    properties:
      district:
        example: Bedford
        type: string
      email:
        example: peter.p@zylker.com
        type: string
      name:
        example: Robert Robertson
        type: string
      ownerId:
        example: 07e7a76c-1bbb-11ed-861d-0242ac120002
        type: string
      phone:
        example: '09832209761'
        type: string
      province:
        example: Titao
        type: string
      status:
        example: Active
        type: string
      street:
        example: 144 J B Hazra Road
        type: string
    type: object
  domain.TeamMember:
    properties:
      birthDate:
        example: '1991-05-06'
        type: string
      district:
        example: Bedford
        type: string
      email:
        example: peter.p@zylker.com
        type: string
      firstName:
        example: Robert
        type: string
      id:
        example: 6a077d3c-1bbb-11ed-861d-0242ac120002
        type: string
      lastName:
        example: Robertson
        type: string
      hostelCode:
        example: 07e7a76c-1bbb-11ed-861d-0242ac120002
        type: string
      nationality:
        example: Afghanistan
        type: string
      password:
        example: Password@3
        type: string
      phone:
        type: string
      province:
        example: Titao
        type: string
      role:
        example: Owner or Manager or Staff
        type: string
      street:
        example: 144 J B Hazra Road
        type: string
      username:
        example: robertson
        type: string
    type: object
  domain.User:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  util.Pagination:
    properties:
      pageIdx:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  util.Response:
    properties:
      data: {}
      error: {}
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: '1.0'
paths:
  /auth/login:
    post:
      consumes:
        - application/json
      parameters:
        - description: User to login
          in: body
          name: User
          required: true
          schema:
            $ref: '#/definitions/domain.User'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.User'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Login
      tags:
        - Users
  /auth/register:
    post:
      consumes:
        - application/json
      parameters:
        - description: User to create
          in: body
          name: User
          required: true
          schema:
            $ref: '#/definitions/domain.User'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.User'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Create a User
      tags:
        - Users
  /hostels:
    get:
      consumes:
        - application/json
      description: Return a list of the Hostels included the pagination
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The index of the page start from 0
          example: '0'
          in: query
          name: pageIdx
          required: true
          type: string
        - description: The number of Hostels return on each page
          example: '10'
          in: query
          name: pageSize
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.GetHostelsResponse'
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get Hostels
      tags:
        - Hostels
    post:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: Hostel to create
          in: body
          name: Hostel
          required: true
          schema:
            $ref: '#/definitions/domain.Hostel'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.Hostel'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Create a Hostel
      tags:
        - Hostels
  /hostels/{code}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The code of The Hostel
          in: path
          name: code
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: '1'
          schema:
            type: string
        '404':
          description: '0'
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a Hostel
      tags:
        - Hostels
    get:
      consumes:
        - application/json
      description: Return a Hostel with the code
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGc...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The code of the Hostel
          example: 07e7a76c-1bbb-11ed-861d-0242ac120002
          in: path
          name: code
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.Hostel'
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get a Hostel
      tags:
        - Hostels
    put:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The code of the Hostel
          example: 07e7a76c-1bbb-11ed-861d-0242ac120002
          in: path
          name: code
          required: true
          type: string
        - description: Hostel to update
          in: body
          name: Hostel
          required: true
          schema:
            $ref: '#/definitions/domain.Hostel'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.Hostel'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Update a Hostel
      tags:
        - Hostels
  /team_members:
    get:
      consumes:
        - application/json
      description: Return a list of the TeamMembers included the pagination
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The index of the page start from 0
          in: query
          name: pageIdx
          required: true
          type: string
        - description: The number of TeamMembers return on each page
          in: query
          name: pageSize
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.GetTeamMembersResponse'
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get TeamMembers
      tags:
        - TeamMembers
    post:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: TeamMember to create
          in: body
          name: TeamMember
          required: true
          schema:
            $ref: '#/definitions/domain.TeamMember'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.TeamMember'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Create a TeamMember
      tags:
        - TeamMembers
  /team_members/{code}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The code of The TeamMember
          in: path
          name: code
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: '1'
          schema:
            type: string
        '404':
          description: '0'
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a TeamMember
      tags:
        - TeamMembers
  /team_members/{id}:
    get:
      consumes:
        - application/json
      description: Return a TeamMember with the id
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The id of the TeamMember
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.TeamMember'
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get a TeamMember
      tags:
        - TeamMembers
    put:
      consumes:
        - application/json
      parameters:
        - description: The Authorization
          example: Bearer eyJhbG...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The id of the TeamMember
          in: path
          name: id
          required: true
          type: string
        - description: TeamMember to update
          in: body
          name: TeamMember
          required: true
          schema:
            $ref: '#/definitions/domain.TeamMember'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/util.Response'
              - properties:
                  data:
                    $ref: '#/definitions/domain.TeamMember'
                  value:
                    type: integer
                type: object
        '400':
          description: Invalid character 's' looking for beginning of value
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Update a TeamMember
      tags:
        - TeamMembers
  /team_members/hostels/{code}:
    get:
      consumes:
        - application/json
      description:
        Return a list of the TeamMember belong to a Hostel included the
        pagination
      parameters:
        - description: The Authorization
          example: Bearer eyJhbGci...
          in: header
          name: Authorization
          required: true
          type: string
        - description: The code of the Hostel
          in: path
          name: code
          required: true
          type: string
        - description: The index of the page start from 0
          in: query
          name: pageIdx
          required: true
          type: string
        - description: The number of TeamMembers return on each page
          in: query
          name: pageSize
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.GetTeamMembersResponse'
        '500':
          description: Internal Server Error
          schema:
            type: string
      summary: Get TeamMembers by Hostel's code
      tags:
        - TeamMembers
swagger: '2.0'
